In [2]:
import numpy as np

Q1  Write a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives

In [11]:
print("An Array of 10 Zeroes")
zeros  = np.zeros(10)
print(zeros)

print("An Array of 10 ones
")
ones  = np.ones(10)
print(ones)

print("An Array of 10 fives")
fives = np.full(10,5)
print(fives)

An Array of 10 Zeroes
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An Array of 10 ones
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An Array of 10 fives
[5 5 5 5 5 5 5 5 5 5]


Q2  Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10

In [23]:
ranges = np.arange(2,11).reshape(3,3)
print(ranges)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


Q3 Write a NumPy program to create an array with values ranging from 12 to 38.

In [17]:
rangess = np.arange(12,38)
print(rangess)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


Write a NumPy program to convert a list and tuple into arrays.   
Input: my_list = [1, 2, 3, 4, 5, 6, 7, 8]       
Input: my_tuple = ([8, 4, 6], [1, 2, 3])

In [22]:
my_list = np.array([1,2,3,4,5,6,7,8])
my_tuple = np.array([[8,4,6],[1,2,3]])

print("List to array: ")
print(my_list)

print("\n")

print("Tuple to array: ")
print(my_tuple)

List to array: 
[1 2 3 4 5 6 7 8]


Tuple to array: 
[[8 4 6]
 [1 2 3]]
